spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/springbootdemo
    username: postgres
    password: 556677
  jpa:
    show_sql: true
    format_sql: true
    hibernate:
      ddl-auto: update